---
blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/RHEcosystemAppEng/exhort-java-api/discussions/
    about: You can also use Discussions for questions and ideas.
