---
name: Verify OpenAPI Spec

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Stage"
    types:
      - completed
  repository_dispatch:
    types: [ backend-openapi-spec-modified ]

jobs:
  verify_no_generated:
    runs-on: ubuntu-latest
    name: Verify Backend OpenAPI Spec
    environment: integration
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download OpenAPI spec
        run: >
          wget https://raw.githubusercontent.com/RHEcosystemAppEng/exhort/0.1.x/src/main/resources/META-INF/openapi.yaml
          -O src/main/resources/exhort/openapi.yaml

      - name: Verify nothing was changed
        run: git diff -s --exit-code
